<?php $_helper = $this->helper('IWD\B2B\Helper\Data');
?>
<section class="cms-login-page">
</section>
<section class="cms-b2b-header">
    <header></header>
</section>
<div class="b2b-login-modal fade" id="b2b-login-modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="b2b-login-modal-dialog modal-dialog">
		<div class="b2b-login-modal-content">
			<div class="b2b-login-modal-body b2b-login-form">
				<div class="b2b-wholesale-login">
					<h5><?php echo $_helper->getText('access_login_form/title1');?></h5>
					<form method="post" action="" id="b2b-login-post-form" data-mage-init='{"validation":{}}'>
					    <?php echo $block->getChildHtml('b2b.messages') ?>
						<?php echo $block->getBlockHtml('formkey'); ?>
						<div class="b2b-input-wrapper">
							<label><?php echo __('Email Address') ?></label>
							<div>
								<input type="text" name="login[username]" id="email" class="required-entry validate-email" title="<?php echo __('Email Address') ?>" />
							</div>
						</div>

						<div class="b2b-input-wrapper last">
							<label><?php echo __('Password') ?></label>
							<div>
								<input type="password" name="login[password]" class="required-entry validate-password" id="pass" title="<?php echo __('Password') ?>" />
							</div>
						</div>
						<div class="a-right">
							<a id="b2b-forgot-password" href="<?php echo $block->getUrl('customer/account/forgotpassword')?>"><?php echo __('Forgot password?')?></a>
						</div>
						<button class="action submit primary" type="submit"><?php echo __('Login') ?></button>
					</form>
				</div>
				<div class="b2b-retail-login">
					<h5><?php echo $_helper->getText('access_login_form/title2');?></h5>
					<p><?php echo $_helper->getText('access_login_form/text_above');?></p>
					<div class="b2b-register-btn-container">
					    <a href="<?php echo $block->getRegisterUrl();?>" class="action primary b2b-register">
                  <?php echo $_helper->getText('access_login_form/text_apply');?>
              </a>
					</div>
					<div class="b2b-desc-reg">
						<p><?php echo $_helper->getText('access_login_form/text_below');?></p>
					</div>
					<div class="b2b-iwd-brand-box">
                        <a href="https://www.iwdagency.com/extensions/b2b-ecommerce-suite-m1-m2.html" target="_blank" title='<?php echo __('Magento B2B by')?>'>
                            <span><?php echo __('Magento B2B by')?></span>
                        </a>
                        <a href="https://www.iwdagency.com" target="_blank" class="svg" title='<?php echo __('IWD')?>'>
                            <object type="image/svg+xml" data="<?php echo $block->getViewFileUrl('IWD_B2B::images/iwd-brand.svg'); ?>"><?php echo __('IWD')?></object>
                        </a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "b2blogin": {}
        }
    }
</script>
